/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as marketingRouteRouteImport } from './routes/(marketing)/route'
import { Route as dashboardRouteRouteImport } from './routes/(dashboard)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as marketingIndexRouteImport } from './routes/(marketing)/index'
import { Route as dashboardmainRouteRouteImport } from './routes/(dashboard)/(main)/route'
import { Route as authSignUpIndexRouteImport } from './routes/(auth)/sign-up/index'
import { Route as authSignInIndexRouteImport } from './routes/(auth)/sign-in/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as dashboardBoardBoardIdIndexRouteImport } from './routes/(dashboard)/board/$boardId/index'
import { Route as dashboardmainTemplatesIndexRouteImport } from './routes/(dashboard)/(main)/templates/index'
import { Route as dashboardmainHomeIndexRouteImport } from './routes/(dashboard)/(main)/home/index'
import { Route as dashboardmainBoardsIndexRouteImport } from './routes/(dashboard)/(main)/boards/index'

const authSignUpLazyRouteImport = createFileRoute('/(auth)/sign-up')()
const authSignInLazyRouteImport = createFileRoute('/(auth)/sign-in')()
const dashboardmainTemplatesLazyRouteImport = createFileRoute(
  '/(dashboard)/(main)/templates',
)()
const dashboardmainHomeLazyRouteImport = createFileRoute(
  '/(dashboard)/(main)/home',
)()
const dashboardmainBoardsLazyRouteImport = createFileRoute(
  '/(dashboard)/(main)/boards',
)()

const marketingRouteRoute = marketingRouteRouteImport.update({
  id: '/(marketing)',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardRouteRoute = dashboardRouteRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingIndexRoute = marketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => marketingRouteRoute,
} as any)
const authSignUpLazyRoute = authSignUpLazyRouteImport
  .update({
    id: '/sign-up',
    path: '/sign-up',
    getParentRoute: () => authRouteRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-up/lazy').then((d) => d.Route))
const authSignInLazyRoute = authSignInLazyRouteImport
  .update({
    id: '/sign-in',
    path: '/sign-in',
    getParentRoute: () => authRouteRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-in/lazy').then((d) => d.Route))
const dashboardmainRouteRoute = dashboardmainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const authSignUpIndexRoute = authSignUpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authSignUpLazyRoute,
} as any)
const authSignInIndexRoute = authSignInIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authSignInLazyRoute,
} as any)
const dashboardmainTemplatesLazyRoute = dashboardmainTemplatesLazyRouteImport
  .update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => dashboardmainRouteRoute,
  } as any)
  .lazy(() =>
    import('./routes/(dashboard)/(main)/templates/lazy').then((d) => d.Route),
  )
const dashboardmainHomeLazyRoute = dashboardmainHomeLazyRouteImport
  .update({
    id: '/home',
    path: '/home',
    getParentRoute: () => dashboardmainRouteRoute,
  } as any)
  .lazy(() =>
    import('./routes/(dashboard)/(main)/home/lazy').then((d) => d.Route),
  )
const dashboardmainBoardsLazyRoute = dashboardmainBoardsLazyRouteImport
  .update({
    id: '/boards',
    path: '/boards',
    getParentRoute: () => dashboardmainRouteRoute,
  } as any)
  .lazy(() =>
    import('./routes/(dashboard)/(main)/boards/lazy').then((d) => d.Route),
  )
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardBoardBoardIdIndexRoute =
  dashboardBoardBoardIdIndexRouteImport.update({
    id: '/board/$boardId/',
    path: '/board/$boardId/',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardmainTemplatesIndexRoute =
  dashboardmainTemplatesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => dashboardmainTemplatesLazyRoute,
  } as any)
const dashboardmainHomeIndexRoute = dashboardmainHomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardmainHomeLazyRoute,
} as any)
const dashboardmainBoardsIndexRoute =
  dashboardmainBoardsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => dashboardmainBoardsLazyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof authSignInLazyRouteWithChildren
  '/sign-up': typeof authSignUpLazyRouteWithChildren
  '/': typeof marketingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/boards': typeof dashboardmainBoardsLazyRouteWithChildren
  '/home': typeof dashboardmainHomeLazyRouteWithChildren
  '/templates': typeof dashboardmainTemplatesLazyRouteWithChildren
  '/sign-in/': typeof authSignInIndexRoute
  '/sign-up/': typeof authSignUpIndexRoute
  '/boards/': typeof dashboardmainBoardsIndexRoute
  '/home/': typeof dashboardmainHomeIndexRoute
  '/templates/': typeof dashboardmainTemplatesIndexRoute
  '/board/$boardId/': typeof dashboardBoardBoardIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof marketingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/sign-in': typeof authSignInIndexRoute
  '/sign-up': typeof authSignUpIndexRoute
  '/boards': typeof dashboardmainBoardsIndexRoute
  '/home': typeof dashboardmainHomeIndexRoute
  '/templates': typeof dashboardmainTemplatesIndexRoute
  '/board/$boardId': typeof dashboardBoardBoardIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(dashboard)': typeof dashboardRouteRouteWithChildren
  '/(marketing)': typeof marketingRouteRouteWithChildren
  '/(dashboard)/(main)': typeof dashboardmainRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInLazyRouteWithChildren
  '/(auth)/sign-up': typeof authSignUpLazyRouteWithChildren
  '/(marketing)/': typeof marketingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(dashboard)/(main)/boards': typeof dashboardmainBoardsLazyRouteWithChildren
  '/(dashboard)/(main)/home': typeof dashboardmainHomeLazyRouteWithChildren
  '/(dashboard)/(main)/templates': typeof dashboardmainTemplatesLazyRouteWithChildren
  '/(auth)/sign-in/': typeof authSignInIndexRoute
  '/(auth)/sign-up/': typeof authSignUpIndexRoute
  '/(dashboard)/(main)/boards/': typeof dashboardmainBoardsIndexRoute
  '/(dashboard)/(main)/home/': typeof dashboardmainHomeIndexRoute
  '/(dashboard)/(main)/templates/': typeof dashboardmainTemplatesIndexRoute
  '/(dashboard)/board/$boardId/': typeof dashboardBoardBoardIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sign-in'
    | '/sign-up'
    | '/'
    | '/api/auth/$'
    | '/boards'
    | '/home'
    | '/templates'
    | '/sign-in/'
    | '/sign-up/'
    | '/boards/'
    | '/home/'
    | '/templates/'
    | '/board/$boardId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth/$'
    | '/sign-in'
    | '/sign-up'
    | '/boards'
    | '/home'
    | '/templates'
    | '/board/$boardId'
  id:
    | '__root__'
    | '/(auth)'
    | '/(dashboard)'
    | '/(marketing)'
    | '/(dashboard)/(main)'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(marketing)/'
    | '/api/auth/$'
    | '/(dashboard)/(main)/boards'
    | '/(dashboard)/(main)/home'
    | '/(dashboard)/(main)/templates'
    | '/(auth)/sign-in/'
    | '/(auth)/sign-up/'
    | '/(dashboard)/(main)/boards/'
    | '/(dashboard)/(main)/home/'
    | '/(dashboard)/(main)/templates/'
    | '/(dashboard)/board/$boardId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  dashboardRouteRoute: typeof dashboardRouteRouteWithChildren
  marketingRouteRoute: typeof marketingRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(marketing)': {
      id: '/(marketing)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof marketingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)': {
      id: '/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/': {
      id: '/(marketing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof marketingIndexRouteImport
      parentRoute: typeof marketingRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpLazyRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInLazyRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(dashboard)/(main)': {
      id: '/(dashboard)/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardmainRouteRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(auth)/sign-up/': {
      id: '/(auth)/sign-up/'
      path: '/'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof authSignUpIndexRouteImport
      parentRoute: typeof authSignUpLazyRoute
    }
    '/(auth)/sign-in/': {
      id: '/(auth)/sign-in/'
      path: '/'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof authSignInIndexRouteImport
      parentRoute: typeof authSignInLazyRoute
    }
    '/(dashboard)/(main)/templates': {
      id: '/(dashboard)/(main)/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof dashboardmainTemplatesLazyRouteImport
      parentRoute: typeof dashboardmainRouteRoute
    }
    '/(dashboard)/(main)/home': {
      id: '/(dashboard)/(main)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof dashboardmainHomeLazyRouteImport
      parentRoute: typeof dashboardmainRouteRoute
    }
    '/(dashboard)/(main)/boards': {
      id: '/(dashboard)/(main)/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof dashboardmainBoardsLazyRouteImport
      parentRoute: typeof dashboardmainRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/board/$boardId/': {
      id: '/(dashboard)/board/$boardId/'
      path: '/board/$boardId'
      fullPath: '/board/$boardId/'
      preLoaderRoute: typeof dashboardBoardBoardIdIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/(main)/templates/': {
      id: '/(dashboard)/(main)/templates/'
      path: '/'
      fullPath: '/templates/'
      preLoaderRoute: typeof dashboardmainTemplatesIndexRouteImport
      parentRoute: typeof dashboardmainTemplatesLazyRoute
    }
    '/(dashboard)/(main)/home/': {
      id: '/(dashboard)/(main)/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof dashboardmainHomeIndexRouteImport
      parentRoute: typeof dashboardmainHomeLazyRoute
    }
    '/(dashboard)/(main)/boards/': {
      id: '/(dashboard)/(main)/boards/'
      path: '/'
      fullPath: '/boards/'
      preLoaderRoute: typeof dashboardmainBoardsIndexRouteImport
      parentRoute: typeof dashboardmainBoardsLazyRoute
    }
  }
}

interface authSignInLazyRouteChildren {
  authSignInIndexRoute: typeof authSignInIndexRoute
}

const authSignInLazyRouteChildren: authSignInLazyRouteChildren = {
  authSignInIndexRoute: authSignInIndexRoute,
}

const authSignInLazyRouteWithChildren = authSignInLazyRoute._addFileChildren(
  authSignInLazyRouteChildren,
)

interface authSignUpLazyRouteChildren {
  authSignUpIndexRoute: typeof authSignUpIndexRoute
}

const authSignUpLazyRouteChildren: authSignUpLazyRouteChildren = {
  authSignUpIndexRoute: authSignUpIndexRoute,
}

const authSignUpLazyRouteWithChildren = authSignUpLazyRoute._addFileChildren(
  authSignUpLazyRouteChildren,
)

interface authRouteRouteChildren {
  authSignInLazyRoute: typeof authSignInLazyRouteWithChildren
  authSignUpLazyRoute: typeof authSignUpLazyRouteWithChildren
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSignInLazyRoute: authSignInLazyRouteWithChildren,
  authSignUpLazyRoute: authSignUpLazyRouteWithChildren,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface dashboardmainBoardsLazyRouteChildren {
  dashboardmainBoardsIndexRoute: typeof dashboardmainBoardsIndexRoute
}

const dashboardmainBoardsLazyRouteChildren: dashboardmainBoardsLazyRouteChildren =
  {
    dashboardmainBoardsIndexRoute: dashboardmainBoardsIndexRoute,
  }

const dashboardmainBoardsLazyRouteWithChildren =
  dashboardmainBoardsLazyRoute._addFileChildren(
    dashboardmainBoardsLazyRouteChildren,
  )

interface dashboardmainHomeLazyRouteChildren {
  dashboardmainHomeIndexRoute: typeof dashboardmainHomeIndexRoute
}

const dashboardmainHomeLazyRouteChildren: dashboardmainHomeLazyRouteChildren = {
  dashboardmainHomeIndexRoute: dashboardmainHomeIndexRoute,
}

const dashboardmainHomeLazyRouteWithChildren =
  dashboardmainHomeLazyRoute._addFileChildren(
    dashboardmainHomeLazyRouteChildren,
  )

interface dashboardmainTemplatesLazyRouteChildren {
  dashboardmainTemplatesIndexRoute: typeof dashboardmainTemplatesIndexRoute
}

const dashboardmainTemplatesLazyRouteChildren: dashboardmainTemplatesLazyRouteChildren =
  {
    dashboardmainTemplatesIndexRoute: dashboardmainTemplatesIndexRoute,
  }

const dashboardmainTemplatesLazyRouteWithChildren =
  dashboardmainTemplatesLazyRoute._addFileChildren(
    dashboardmainTemplatesLazyRouteChildren,
  )

interface dashboardmainRouteRouteChildren {
  dashboardmainBoardsLazyRoute: typeof dashboardmainBoardsLazyRouteWithChildren
  dashboardmainHomeLazyRoute: typeof dashboardmainHomeLazyRouteWithChildren
  dashboardmainTemplatesLazyRoute: typeof dashboardmainTemplatesLazyRouteWithChildren
}

const dashboardmainRouteRouteChildren: dashboardmainRouteRouteChildren = {
  dashboardmainBoardsLazyRoute: dashboardmainBoardsLazyRouteWithChildren,
  dashboardmainHomeLazyRoute: dashboardmainHomeLazyRouteWithChildren,
  dashboardmainTemplatesLazyRoute: dashboardmainTemplatesLazyRouteWithChildren,
}

const dashboardmainRouteRouteWithChildren =
  dashboardmainRouteRoute._addFileChildren(dashboardmainRouteRouteChildren)

interface dashboardRouteRouteChildren {
  dashboardmainRouteRoute: typeof dashboardmainRouteRouteWithChildren
  dashboardBoardBoardIdIndexRoute: typeof dashboardBoardBoardIdIndexRoute
}

const dashboardRouteRouteChildren: dashboardRouteRouteChildren = {
  dashboardmainRouteRoute: dashboardmainRouteRouteWithChildren,
  dashboardBoardBoardIdIndexRoute: dashboardBoardBoardIdIndexRoute,
}

const dashboardRouteRouteWithChildren = dashboardRouteRoute._addFileChildren(
  dashboardRouteRouteChildren,
)

interface marketingRouteRouteChildren {
  marketingIndexRoute: typeof marketingIndexRoute
}

const marketingRouteRouteChildren: marketingRouteRouteChildren = {
  marketingIndexRoute: marketingIndexRoute,
}

const marketingRouteRouteWithChildren = marketingRouteRoute._addFileChildren(
  marketingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  dashboardRouteRoute: dashboardRouteRouteWithChildren,
  marketingRouteRoute: marketingRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
